apiVersion: v1
baseDomain: localdomain
compute:
- hyperthreading: Enabled 
  name: worker
  replicas: 0 
controlPlane:
  hyperthreading: Enabled 
  name: master 
  replicas: 1
metadata:
  name: ocp43
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {} 
fips: false 
pullSecret: '{"auths":{"registry.ocp43.localdomain:5000": {"auth": "YWRtaW46YWRtaW4=","email": "afuentes@gbm.net"}}}' 
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDd1TRijO0tNJsHw6253Xjwk90zBYiaidGQ8luBZlkGvJ4DwBKevX1fOBh0AWsOfJ/+ehbR4hMe4h14+nU7tl3eooXKq4m0we13GMH/VeMgAR262p0vz3Hx1+EJ1fvcODy0vhmF68wc7vWFEbS1+Dsa47Y40D8FNhZqZlZ8NeGcehIBhP5hw/598eoA9M+kBcBf+7Dmid5kEfgGPHzrYQ4+FK6TeUohFMCgRvUQ3nY6ob0AhbOl8jJQTlUlUDnQcFeyCeP+pXCdQAEJgzIbjYmF+lS7FsokJVqzjCgLq9dpSgz9xsWR73j2GFP9lc0ZACzy9BDjtl458HeWvVSSC2yfGZqpqnopc3jKMX3j83mspqwENKHskwHfTpyz673J9zHT7LASU4ye6mPIlSxiMx9dYtbrHsycA6QUZ2voCFVZ/wXTZ2CP9uvc1jbOTtyA3bYQdUkhV5jQax0Ni036strwu7PalPbwtI5Ta2jHtVe7RWXAuh15rk8jqh3PWt9G0XHpLIPIkcUlOsPzFEpiopuzadLytE5QIU4JTnN0cD+DHzKiHSMM+DDpMPoC/fuKP4yQdHD9hnrSMtbYVgH61SH45CkI34xE9QKb6EUsHV6NDEQ5hfc42yq3EmbOR3rBlivNFm9orH7RNO2ss8UAF9Ke/yUqSNx3WrYzcChhiZICKw== root@bastion.ocp43.localdomain'
additionalTrustBundle: | 
  -----BEGIN CERTIFICATE-----
  MIIGAzCCA+ugAwIBAgIURJZkiSR8U6DZLwlqnxlnZ+jKUhwwDQYJKoZIhvcNAQEL
  BQAwgZAxCzAJBgNVBAYTAkNSMRAwDgYDVQQIDAdDYXJ0YWdvMQ4wDAYDVQQHDAVU
  ZWphcjEMMAoGA1UECgwDR0JNMQswCQYDVQQLDAJTVzEjMCEGA1UEAwwacmVnaXN0
  cnkub2NwNDMubG9jYWxkb21haW4xHzAdBgkqhkiG9w0BCQEWEGFmdWVudGVzQGdi
  bS5uZXQwHhcNMjAwNjE5MTgxMDMzWhcNMjEwNjE5MTgxMDMzWjCBkDELMAkGA1UE
  BhMCQ1IxEDAOBgNVBAgMB0NhcnRhZ28xDjAMBgNVBAcMBVRlamFyMQwwCgYDVQQK
  DANHQk0xCzAJBgNVBAsMAlNXMSMwIQYDVQQDDBpyZWdpc3RyeS5vY3A0My5sb2Nh
  bGRvbWFpbjEfMB0GCSqGSIb3DQEJARYQYWZ1ZW50ZXNAZ2JtLm5ldDCCAiIwDQYJ
  KoZIhvcNAQEBBQADggIPADCCAgoCggIBAK5sZmN1WrRQUfHtvlbDN9DEhgKXoHjm
  4Vgh7NIy/Q+BzmZ1Q2wCaJxP0Yyl77JWtwo0SUsXWnHacFRLClr9EDVI3rPjlI+r
  gglnIK857+xKmxbyolWpDhu1e0TO9QttMLxwJuYUqbK2WPQaOiA/ElxsRJNrIBbI
  i3IHPJ6jke7RaNjt5jJKfvxvxS+XfLoyQJIAnUIbt37oCcA5I0018IfeVlvZZ9yz
  dBiEUfjuJ1p4MSxfRAFsr1lfNhcazeco72Vp0L1pv3Pt93o9m5ugd3RicRDaLLRt
  uUpeXYYtOMeaxoM9G02/dl07BbxQINWWcK+7eOBixCMpafMtl41M0OgEkjPf5ADd
  bWXCYDQ37SHxZr8q18DgvStIcaVVs5AmQR//MljVoSmF0D4S8GvFS1oo+nVfDd9/
  g+GA3EO1Ct9ZQk/chTWIOXX9jMo7u672w66m6Rw9pALvwTmjvbTIKvWgGlNk8Wgf
  bJzFyGd0AwV/13+gefALFU5TxoDsWxEQyQLCVyQynNK4dgIfdqIGHNHbw/B3H8gL
  ROCBAIRKBZ/hgP8+XSPCNNLNTvlonzg3EzVSKp2cNzfhc1dvYOLIcaYl1E56SuGa
  g6/3xbLWekdNO9R7YhwpGyySdolKSthFjeGIZlU8Rn123MjLP1+LiHcOysrBVv0+
  EkMS7AqLTnaNAgMBAAGjUzBRMB0GA1UdDgQWBBS9BxIcG/uWfCXuncAxD4J6fVyr
  nzAfBgNVHSMEGDAWgBS9BxIcG/uWfCXuncAxD4J6fVyrnzAPBgNVHRMBAf8EBTAD
  AQH/MA0GCSqGSIb3DQEBCwUAA4ICAQABA07GwNAAAni0NYtnlbrLrCyb8h/hW951
  RsQI7lbBUAoHn1OJZz1G2mM6WFnXsgHpDqopX/4z1pi/N7zR+1hKSN1qFkZwGfhn
  q9klYSlglE0oGQ1WTZbXFle9CnLxnHa5J/nV0WTpXw/8t/9yQgaI8xiWXIufnGmb
  agURsGi69ptIPL7+K7bDolmTlA7J15Va1+ShwBEnFxDnQ2vrByb1nMgATpRkhgMZ
  ff8XDrEPzjmRcuwTbAcPPZv7jYARwNXQyteoby7Shh9QZFA/K79bmh+DfZvhoyNy
  RXnYEPRcQYiphdPVEy4UjtbOUyW9Li0RaBNsrZgIkMx8ZowNnIUPaIjp9y+aDMFF
  1UMQjil4zc5sP0SqzT2v1yTHPYuWxQLQZv8qUAGyAoeri+d0xjPQmFRY6vKBAcs6
  CC7x1Qaru3LudvCsMrx+I9Bq4sIrn+1Z84nZoECG8AzFo8NPmOyuidxMg+EaK+4K
  clJCVZuTHTUpBNvnRfp2hpoP8sRuJqL34WDbcHHzgMDJViYApiKvmNzSQ3N1KWxq
  0jIi8048mLuGdtvGtMQai9MdbOQx0rZsneD3MaV5A8aGk5Yfq9rHEycNn0mrnfrt
  tl/FXMvCgCPVRzOIi6VjXw+1/cr/4NqM0/oLLYcG7F+Lf7c5xQr67qfrvsvuke/L
  64/DbO54Tg==
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - registry.ocp43.localdomain:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - registry.ocp43.localdomain:5000/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
